version: '3.7'

services:
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: partenaire
      POSTGRES_USER: partenaire
      POSTGRES_PASSWORD: pwd
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'

  database-admin:
    image: adminer
    ports:
      - 8080:8080
    expose:
      - '8080'
    depends_on:
      - database

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootAdmin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: core-fca-low
    volumes:
      - './mongodb/initdb.d:/docker-entrypoint-initdb.d'

  mongo-express:
    image: mongo-express:1.0
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootAdmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: pass
      ME_CONFIG_MONGODB_URL: mongodb://rootAdmin:pass@mongo:27017/
    depends_on:
      - mongo
