version: '3.7'

services:
  database:
    build:
      context: ./db
    restart: always
    environment:
      POSTGRES_DB: partenaire
      POSTGRES_USER: partenaire
      POSTGRES_PASSWORD: pwd
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'

  database-admin:
    image: adminer
    ports:
      - 8080:8080
    expose:
      - '8080'
    depends_on:
      - database
