#

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: package.json
      - run: npm ci
        working-directory: ./front
      - run: npm run build
        working-directory: ./front

  back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version-file: package.json
      - run: npm ci
        working-directory: ./back
      - run: npm run build
        working-directory: ./back
