#

name: Publish

on:
  push:
    branches:
      - main
      - alpha

  workflow_dispatch:

permissions:
  packages: write

jobs:
  build:
    name: Publich Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/betagouv/espace-partenaire
          tags: |
            type=sha,format=long,prefix=
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=${{ github.ref == 'refs/heads/main' }}

      - uses: actions/checkout@v3
      - name: Build image
        uses: docker/build-push-action@v3
        with:
          build-args: |
            SOURCE_COMMIT=${{ github.sha }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max
          context: ./back
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
